services:
  web:
    image: haki2/re:latest
    build:
      context: ./
      dockerfile: dockerfile.prod
    container_name: 'recruto-docker'
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000:5000
    env_file:
      - ./.env.prod
  nginx:
    image: haki2/re:latest2
    build:
      context: ./nginx
    restart: always
    ports:
      - 1337:80
    depends_on:
      - web